spring:
  application:
    name: aboa
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/aboa}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

    spring:
      servlet:
        multipart:
          max-file-size: 5MB
          max-request-size: 5MB

jwt:
  key: ${JWT_KEY:gFyEl1eXu7vgK%5hNug4R$peuzZTYPabTBt64rf7EB5ul^GPr#DJAoFY@3ZqBEjLtz%Md#lwj7RQQDR43XvWqBAifClfKEUDh3jh^zI!rEUX9yvSwWAJmQib95nuSjq1z&qYBR73V9weao4pDb5wzL6Y299W#Us#w3KbSbjbEitksv$fGwG%l8dRQgf3ec0xP1iOu@^tAQ^1lHBtYZhR2ZUfLYL#pV$x9X56JGLx7jZY@GBrN&olbaU8^O&EH@Hr0j3i%dQH0yBe8ldflhsXW7pY$5!mT7WnTv4%GGCd3&yb^BgyA$%yyB@!DPHHwXSXlB2t7glITx0$#GkBD7CjEi5P}
